version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=twipost.settings
    depends_on:
      - db
    networks:
      - twibase_network

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=twibase_db
      - POSTGRES_USER=twibase_user
      - POSTGRES_PASSWORD=twibase_password
    ports:
      - "5432:5432"
    networks:
      - twibase_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - twibase_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  twibase_network:
    driver: bridge
